Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2020
Var
// Seção de Declarações das variáveis 
x: inteiro
 
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("Digite o valor de x")
   leia(x)
   se x=5 entao
    escreval("O valor de x é 5")
   senao
    escreval("O valor de x nao é 5")
   fimse

 Fimalgoritmo